name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: hml

    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      IMAGE_NAME: ${{secrets.ACR_LOGIN_SERVER}}/${{ github.event.repository.name }}:${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name "$ACR_NAME"

      - name: Build Docker image
        run: |
          docker build \
            --tag "$IMAGE_NAME" \
            .

      - name: Push Docker image
        run: docker push "$IMAGE_NAME"

      - name: Show published image
        run: |
          echo "Image published:"
          echo "$IMAGE_NAME"
